title: [LeadSheetLoop]
description: [AI Loop Generator for Composer's reference]
#logo: /AI Loops.png

Music and Audio Computing Lab
Research Center for IT Innovation
Academia Sinica

theme: jekyll-theme-minimal
