title: [LeadSheetLoop]
description: [AI Loop Generator for Composer's reference]
#logo: /AI Loops.png
markdown: Music and Audio Computing Lab
markdown: Research Center for IT Innovation
markdown: Academia Sinica
theme: jekyll-theme-minimal
