title: [LeadSheetLoop]
description: [AI Loop Generator for Composer's reference]
#logo: /AI Loops.png
#kramdown: Music and Audio Computing Lab
#kramdown: Research Center for IT Innovation
#kramdown: Academia Sinica
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
theme: jekyll-theme-minimal
